apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: signoz-stripprefix
  namespace: devquote
  labels:
    app: signoz
    component: observability
spec:
  stripPrefix:
    prefixes:
      - /signoz
